server.port: 8080
spring:
  application.name: toshiro-shibakita
  datasource:
    url: jdbc:mysql://{DB_HOST:localhost}/shibakita?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    #Alterar para create-drop em caso de mudanca do schema
    hibernate.ddl-auto: update
    show-sql: true